FROM rust:1.82 AS rust

WORKDIR /usr/app

COPY crates crates
COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock
COPY relay.toml relay.toml
RUN cargo build --release --bin polysig-keygen --bin polysig-relay
RUN target/release/polysig-keygen keypair server.pem
CMD target/release/polysig-relay relay.toml
