FROM rust:1.82 AS rust

WORKDIR /usr/app

COPY crates crates
COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock
COPY meeting.toml meeting.toml
RUN cargo build --release --bin polysig-meeting
CMD target/release/polysig-meeting meeting.toml
