extend= [
  { path = "coverage.toml" }
]
[config]
default_to_workspace = false
skip_core_tasks = true

[env]
RUST_BACKTRACE = 0

[tasks.check]
command = "cargo"
args = ["hack", "check", "--all", "--each-feature"]

[tasks.release]
command = "cargo"
args = ["build", "--bins", "--all", "--release"]

[tasks.doc]
toolchain = "nightly"
command = "cargo"
args = ["doc", "--workspace", "--open", "--no-deps", "--all-features"]

[tasks.unit]
command = "cargo"
args = ["nextest", "run", "--all", "--lib"]

[tasks.integration]
command = "cargo"
args = [
  "nextest",
  "run",
  "-p",
  "polysig-integration-tests",
  "--all-features",
]

[tasks.test]
dependencies = ["unit", "integration"]

[tasks.dev]
dependencies = ["check-wasm", "test", "format"]

[tasks.wasm-bindings]
script = '''
cd bindings/webassembly
wasm-pack build --target web --scope mpc-sdk --features full
'''

[tasks.wasm-bindings-debug]
script = '''
cd bindings/webassembly
wasm-pack build --target web --scope mpc-sdk --features tracing,full
'''

[tasks.wasm-signers]
script = '''
cd bindings/webassembly
wasm-pack build --target web --scope mpc-sdk --features signers
'''

[tasks.wasm-protocols]
script = '''
cd bindings/webassembly
wasm-pack build --target web --scope mpc-sdk --features signers
'''

[tasks.gen-server-key]
script = '''
cargo run -- generate-keypair server.pem
'''

[tasks.gen-keys]
script = '''
cargo run -- generate-keypair tests/test.pem --public-key tests/server_public_key.txt
cargo run -- generate-keypair conformance/signers/webassembly-cggmp/p1.pem
cargo run -- generate-keypair conformance/signers/webassembly-cggmp/p2.pem
cargo run -- generate-keypair conformance/signers/webassembly-cggmp/p3.pem

cargo run -- generate-keypair conformance/signers/node-cggmp/p1.pem
cargo run -- generate-keypair conformance/signers/node-cggmp/p2.pem
cargo run -- generate-keypair conformance/signers/node-cggmp/p3.pem
'''
dependencies = ["gen-server-key"]

[tasks.test-server]
script = '''
cargo run -- start -b 127.0.0.1:8008 integration_tests/tests/config.toml
'''

[tasks.genhtml]
script = '''
grcov ${COVERAGE_PROF_OUTPUT} -s . --binary-path ./target/cover/debug -t html --branch --ignore-not-existing -o ./target/coverage/ --ignore '*/build.rs' --ignore 'tests/*' --ignore 'target/*' --ignore 'src/*'
'''

[tasks.coverage]
alias = "coverage_grcov"
dependencies = ["clean-profraw"]

[tasks.clean-profraw]
script = '''
rm -f *.profraw
rm -f client/*.profraw
rm -f protocol/*.profraw
rm -f server/*.profraw
'''

[tasks.clean-coverage]
command = "cargo"
args = ["clean", "--target-dir", "target/coverage"]

[tasks.clean-cover]
command = "cargo"
args = ["clean", "--target-dir", "target/cover"]

[tasks.cover]
dependencies = ["clean-cover", "clean-coverage", "coverage", "genhtml", "clean-profraw"]
