[package]
name = "mpc-relay"
version = "0.7.0"
edition = "2021"
description = "Noise protocol websocket relay for MPC/TSS applications"
keywords = ["mpc", "tss", "relay", "crypto", "e2ee"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/mpc-sdk/framework"

[dependencies]
mpc-protocol.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
mpc-relay-server.workspace = true
clap.workspace = true
tokio.workspace = true
axum-server.workspace = true
