key = "../integration_tests/tests/test.pem"

# speed up polling for webassembly CGGMP tests (wait-interval)
# but keep the standard timeout setting (wait-timeout)
[session]
timeout = 300
interval = 900
wait-interval = 1
wait-timeout = 60
