use thiserror::Error;

/// Errors generated by the protocol.
#[derive(Debug, Error)]
pub enum Error {

    /// Key generation error.
    #[error(transparent)]
    Keygen(#[from] multi_party_ecdsa::protocols::multi_party_ecdsa::gg_2020::state_machine::keygen::Error),
}
