/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Signer for EdDSA. */
export declare class EddsaSigner {
  /** Create a new signer. */
  constructor(signingKey: Array<number>)
  /** Generate a random signing key. */
  static random(): Array<number>
  /** Sign a message. */
  sign(message: Array<number>): Array<number>
  /** Verifying key for this signer. */
  verifyingKey(): Array<number>
  /** Verify a message. */
  verify(message: Array<number>, signature: Array<number>): void
}
